# Ruff configuration file
# This file can be used instead of pyproject.toml for ruff-specific settings

target-version = "py310"
line-length = 88

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "S",   # flake8-bandit (security)
    "T20", # flake8-print
    "SIM", # flake8-simplify
    "RUF", # ruff-specific rules
]

ignore = [
    "E501",  # line too long, handled by formatter
    "B008",  # do not perform function calls in argument defaults
    "S101",  # use of assert detected (allow in tests)
    "T201",  # print found (allow for CLI tools)
]

[lint.per-file-ignores]
"tests/*" = ["S101", "B011"]  # Allow assert and function calls in defaults for tests
"main.py" = ["T201"]          # Allow print in main CLI file

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.isort]
known-first-party = ["server"]
force-single-line = false
combine-as-imports = true